version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  api:
    build: .
    image: app_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
